# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Get current time
    #   uses: gerred/actions/current-time@master
    #   id: current-time


    # - name: Docker login
    #   uses: actions/docker/login@master
    #   env:
    #     DOCKER_REGISTRY_URL: "registry.hub.docker.com"
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      # if: success()

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tags: ${{ github.ref }}-continuous-${{ github.run_number }}
        tag_with_ref: true
        tag_with_sha: true
        push: true
        add_git_labels: true

    # - name: Docker build
    #   uses: actions/docker/cli@master
    #   with:
    #     args: "build -t ${{ github.repository }}:${{ github.ref }}-continuous-${{ github.run_number }} -t ${{ github.repository }}:${{ github.ref }}-${{ steps.current-time.outputs.time }}  -t ${{ github.repository }}:${{ github.ref }}:${{ github.sha }} ."
